// Code generated by ent, DO NOT EDIT.

package session

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/ai-logger/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldID, id))
}

// Tool applies equality check predicate on the "tool" field. It's identical to ToolEQ.
func Tool(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTool, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProject, v))
}

// SessionName applies equality check predicate on the "session_name" field. It's identical to SessionNameEQ.
func SessionName(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSessionName, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEndedAt, v))
}

// EntryCount applies equality check predicate on the "entry_count" field. It's identical to EntryCountEQ.
func EntryCount(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEntryCount, v))
}

// ToolEQ applies the EQ predicate on the "tool" field.
func ToolEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTool, v))
}

// ToolNEQ applies the NEQ predicate on the "tool" field.
func ToolNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldTool, v))
}

// ToolIn applies the In predicate on the "tool" field.
func ToolIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldTool, vs...))
}

// ToolNotIn applies the NotIn predicate on the "tool" field.
func ToolNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldTool, vs...))
}

// ToolGT applies the GT predicate on the "tool" field.
func ToolGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldTool, v))
}

// ToolGTE applies the GTE predicate on the "tool" field.
func ToolGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldTool, v))
}

// ToolLT applies the LT predicate on the "tool" field.
func ToolLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldTool, v))
}

// ToolLTE applies the LTE predicate on the "tool" field.
func ToolLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldTool, v))
}

// ToolContains applies the Contains predicate on the "tool" field.
func ToolContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldTool, v))
}

// ToolHasPrefix applies the HasPrefix predicate on the "tool" field.
func ToolHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldTool, v))
}

// ToolHasSuffix applies the HasSuffix predicate on the "tool" field.
func ToolHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldTool, v))
}

// ToolEqualFold applies the EqualFold predicate on the "tool" field.
func ToolEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldTool, v))
}

// ToolContainsFold applies the ContainsFold predicate on the "tool" field.
func ToolContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldTool, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldProject, v))
}

// SessionNameEQ applies the EQ predicate on the "session_name" field.
func SessionNameEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldSessionName, v))
}

// SessionNameNEQ applies the NEQ predicate on the "session_name" field.
func SessionNameNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldSessionName, v))
}

// SessionNameIn applies the In predicate on the "session_name" field.
func SessionNameIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldSessionName, vs...))
}

// SessionNameNotIn applies the NotIn predicate on the "session_name" field.
func SessionNameNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldSessionName, vs...))
}

// SessionNameGT applies the GT predicate on the "session_name" field.
func SessionNameGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldSessionName, v))
}

// SessionNameGTE applies the GTE predicate on the "session_name" field.
func SessionNameGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldSessionName, v))
}

// SessionNameLT applies the LT predicate on the "session_name" field.
func SessionNameLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldSessionName, v))
}

// SessionNameLTE applies the LTE predicate on the "session_name" field.
func SessionNameLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldSessionName, v))
}

// SessionNameContains applies the Contains predicate on the "session_name" field.
func SessionNameContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldSessionName, v))
}

// SessionNameHasPrefix applies the HasPrefix predicate on the "session_name" field.
func SessionNameHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldSessionName, v))
}

// SessionNameHasSuffix applies the HasSuffix predicate on the "session_name" field.
func SessionNameHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldSessionName, v))
}

// SessionNameEqualFold applies the EqualFold predicate on the "session_name" field.
func SessionNameEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldSessionName, v))
}

// SessionNameContainsFold applies the ContainsFold predicate on the "session_name" field.
func SessionNameContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldSessionName, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldEndedAt))
}

// EntryCountEQ applies the EQ predicate on the "entry_count" field.
func EntryCountEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEntryCount, v))
}

// EntryCountNEQ applies the NEQ predicate on the "entry_count" field.
func EntryCountNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldEntryCount, v))
}

// EntryCountIn applies the In predicate on the "entry_count" field.
func EntryCountIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldEntryCount, vs...))
}

// EntryCountNotIn applies the NotIn predicate on the "entry_count" field.
func EntryCountNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldEntryCount, vs...))
}

// EntryCountGT applies the GT predicate on the "entry_count" field.
func EntryCountGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldEntryCount, v))
}

// EntryCountGTE applies the GTE predicate on the "entry_count" field.
func EntryCountGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldEntryCount, v))
}

// EntryCountLT applies the LT predicate on the "entry_count" field.
func EntryCountLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldEntryCount, v))
}

// EntryCountLTE applies the LTE predicate on the "entry_count" field.
func EntryCountLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldEntryCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
