// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/ai-logger/ent/entry"
)

// Entry is the model entity for the Entry schema.
type Entry struct {
	config `json:"-"`
	// ID of the ent.
	// UUID v7 generated at insert. Time-sortable, globally unique.
	ID string `json:"id,omitempty"`
	// Name of the AI tool that produced this turn.
	// Source: --tool flag on ailog add, or auto-set by per-tool hook adapter
	// (claude-code | codex | opencode | generic | manual).
	Tool string `json:"tool,omitempty"`
	// Version of the AI tool, if known.
	// Source: Claude Code transcript JSONL (top-level "version" field, e.g. "2.1.114").
	// Other tools: empty until their adapters extract it.
	ToolVersion string `json:"tool_version,omitempty"`
	// Working directory at capture time. Source: hook payload cwd OR auto-detected via os.Getwd().
	Cwd string `json:"cwd,omitempty"`
	// Canonical "host/owner/repo" string derived from git remote.
	// Source: cwd → walk up to .git → read remote.origin.url → canonicalize.
	Project string `json:"project,omitempty"`
	// Repo owner (parsed from remote). Source: same as project.
	RepoOwner string `json:"repo_owner,omitempty"`
	// Repo name (parsed from remote). Source: same as project.
	RepoName string `json:"repo_name,omitempty"`
	// Raw remote.origin.url, before canonicalization.
	RepoRemote string `json:"repo_remote,omitempty"`
	// Current git branch at capture time. Source: `git rev-parse --abbrev-ref HEAD` in cwd.
	GitBranch string `json:"git_branch,omitempty"`
	// Short git SHA at capture time. Source: `git rev-parse --short HEAD`.
	GitCommit string `json:"git_commit,omitempty"`
	// Identifier grouping turns from one conversation.
	// Source: hook payload session_id (claude-code: real Claude session UUID;
	// other tools: tool-supplied; manual: --session flag or freshly generated).
	SessionID string `json:"session_id,omitempty"`
	// User-assigned label for the session. Source: ailog session name CLI / web rename.
	SessionName string `json:"session_name,omitempty"`
	// 0-based index within the session. Auto-computed by Store.InsertEntry.
	TurnIndex int `json:"turn_index,omitempty"`
	// ailog id of the previous turn in this session. Auto-linked at insert.
	ParentEntryID string `json:"parent_entry_id,omitempty"`
	// os.Hostname().
	Hostname string `json:"hostname,omitempty"`
	// $USER env var.
	User string `json:"user,omitempty"`
	// basename of $SHELL env var.
	Shell string `json:"shell,omitempty"`
	// $TERM_PROGRAM env var (iTerm.app, ghostty, …).
	Terminal string `json:"terminal,omitempty"`
	// Best-effort terminal title (env-only — see internal/context/env.go).
	TerminalTitle string `json:"terminal_title,omitempty"`
	// Controlling tty path.
	Tty string `json:"tty,omitempty"`
	// Parent process id ($AILOG_PARENT_PID env or os.Getppid()).
	Pid int `json:"pid,omitempty"`
	// The user's prompt text, secret-scrubbed. Source: hook prompt field / --prompt flag / stdin.
	Prompt string `json:"prompt,omitempty"`
	// The assistant's response text, secret-scrubbed.
	// Source: claude-code Stop hook — prefers payload.last_assistant_message
	// (race-free) and falls back to parsing the transcript jsonl.
	Response string `json:"response,omitempty"`
	// Model identifier (e.g. "claude-opus-4-7").
	// Source: Claude Code transcript message.model. Other tools: --model flag.
	Model string `json:"model,omitempty"`
	// Free-form provenance blob. Currently used for:
	// - claude-code: stores transcript_path so we can re-derive metadata if needed.
	// - ailog import: SHA-256 hash of the source JSONL line, for idempotent backfill.
	Raw string `json:"raw,omitempty"`
	// Input tokens billed for this turn.
	// Source: Claude Code Stop hook — transcript message.usage.input_tokens.
	// Other tools: 0 unless adapter populates it.
	TokenCountIn int `json:"token_count_in,omitempty"`
	// Output tokens generated by the assistant for this turn.
	// Source: Claude Code Stop hook — transcript message.usage.output_tokens.
	TokenCountOut int `json:"token_count_out,omitempty"`
	// Tokens served from Anthropic's prompt cache (cache HIT).
	// Source: Claude Code Stop hook — transcript message.usage.cache_read_input_tokens.
	// High value = cache hit %; cheap turns. Anthropic-specific (zero for non-Claude tools).
	TokenCountCacheRead int `json:"token_count_cache_read,omitempty"`
	// Tokens written into Anthropic's prompt cache (cache MISS / write).
	// Source: Claude Code Stop hook — transcript message.usage.cache_creation_input_tokens.
	// Anthropic-specific.
	TokenCountCacheCreate int `json:"token_count_cache_create,omitempty"`
	// Why the assistant stopped this turn.
	// Source: Claude Code Stop hook — transcript message.stop_reason.
	// Common values: "end_turn" (normal), "tool_use" (mid-turn tool call),
	// "max_tokens" (hit output cap), "stop_sequence". Distinguishes complete
	// responses from interrupted ones for filtering / debugging.
	StopReason string `json:"stop_reason,omitempty"`
	// Claude Code permission mode at the moment of capture.
	// Source: Claude Code hook payload "permission_mode" field
	// (UserPromptSubmit and Stop both carry it).
	// Values: "default" | "acceptEdits" | "bypassPermissions" | "plan".
	// Lets you filter "everything I did in plan mode" or audit YOLO sessions.
	PermissionMode string `json:"permission_mode,omitempty"`
	// CSV of user-applied tags. Edited via ailog tag / web tag form.
	Tags string `json:"tags,omitempty"`
	// User flag for templates / keepers.
	Starred bool `json:"starred,omitempty"`
	// Free-form user annotation, markdown supported.
	Notes string `json:"notes,omitempty"`
	// Insert wall time (UTC).
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Entry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entry.FieldStarred:
			values[i] = new(sql.NullBool)
		case entry.FieldTurnIndex, entry.FieldPid, entry.FieldTokenCountIn, entry.FieldTokenCountOut, entry.FieldTokenCountCacheRead, entry.FieldTokenCountCacheCreate:
			values[i] = new(sql.NullInt64)
		case entry.FieldID, entry.FieldTool, entry.FieldToolVersion, entry.FieldCwd, entry.FieldProject, entry.FieldRepoOwner, entry.FieldRepoName, entry.FieldRepoRemote, entry.FieldGitBranch, entry.FieldGitCommit, entry.FieldSessionID, entry.FieldSessionName, entry.FieldParentEntryID, entry.FieldHostname, entry.FieldUser, entry.FieldShell, entry.FieldTerminal, entry.FieldTerminalTitle, entry.FieldTty, entry.FieldPrompt, entry.FieldResponse, entry.FieldModel, entry.FieldRaw, entry.FieldStopReason, entry.FieldPermissionMode, entry.FieldTags, entry.FieldNotes:
			values[i] = new(sql.NullString)
		case entry.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Entry fields.
func (_m *Entry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entry.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case entry.FieldTool:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tool", values[i])
			} else if value.Valid {
				_m.Tool = value.String
			}
		case entry.FieldToolVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tool_version", values[i])
			} else if value.Valid {
				_m.ToolVersion = value.String
			}
		case entry.FieldCwd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cwd", values[i])
			} else if value.Valid {
				_m.Cwd = value.String
			}
		case entry.FieldProject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project", values[i])
			} else if value.Valid {
				_m.Project = value.String
			}
		case entry.FieldRepoOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_owner", values[i])
			} else if value.Valid {
				_m.RepoOwner = value.String
			}
		case entry.FieldRepoName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_name", values[i])
			} else if value.Valid {
				_m.RepoName = value.String
			}
		case entry.FieldRepoRemote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_remote", values[i])
			} else if value.Valid {
				_m.RepoRemote = value.String
			}
		case entry.FieldGitBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field git_branch", values[i])
			} else if value.Valid {
				_m.GitBranch = value.String
			}
		case entry.FieldGitCommit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field git_commit", values[i])
			} else if value.Valid {
				_m.GitCommit = value.String
			}
		case entry.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case entry.FieldSessionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_name", values[i])
			} else if value.Valid {
				_m.SessionName = value.String
			}
		case entry.FieldTurnIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field turn_index", values[i])
			} else if value.Valid {
				_m.TurnIndex = int(value.Int64)
			}
		case entry.FieldParentEntryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_entry_id", values[i])
			} else if value.Valid {
				_m.ParentEntryID = value.String
			}
		case entry.FieldHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname", values[i])
			} else if value.Valid {
				_m.Hostname = value.String
			}
		case entry.FieldUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user", values[i])
			} else if value.Valid {
				_m.User = value.String
			}
		case entry.FieldShell:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shell", values[i])
			} else if value.Valid {
				_m.Shell = value.String
			}
		case entry.FieldTerminal:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field terminal", values[i])
			} else if value.Valid {
				_m.Terminal = value.String
			}
		case entry.FieldTerminalTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field terminal_title", values[i])
			} else if value.Valid {
				_m.TerminalTitle = value.String
			}
		case entry.FieldTty:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tty", values[i])
			} else if value.Valid {
				_m.Tty = value.String
			}
		case entry.FieldPid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pid", values[i])
			} else if value.Valid {
				_m.Pid = int(value.Int64)
			}
		case entry.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case entry.FieldResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value.Valid {
				_m.Response = value.String
			}
		case entry.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case entry.FieldRaw:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw", values[i])
			} else if value.Valid {
				_m.Raw = value.String
			}
		case entry.FieldTokenCountIn:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_count_in", values[i])
			} else if value.Valid {
				_m.TokenCountIn = int(value.Int64)
			}
		case entry.FieldTokenCountOut:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_count_out", values[i])
			} else if value.Valid {
				_m.TokenCountOut = int(value.Int64)
			}
		case entry.FieldTokenCountCacheRead:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_count_cache_read", values[i])
			} else if value.Valid {
				_m.TokenCountCacheRead = int(value.Int64)
			}
		case entry.FieldTokenCountCacheCreate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_count_cache_create", values[i])
			} else if value.Valid {
				_m.TokenCountCacheCreate = int(value.Int64)
			}
		case entry.FieldStopReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stop_reason", values[i])
			} else if value.Valid {
				_m.StopReason = value.String
			}
		case entry.FieldPermissionMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission_mode", values[i])
			} else if value.Valid {
				_m.PermissionMode = value.String
			}
		case entry.FieldTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value.Valid {
				_m.Tags = value.String
			}
		case entry.FieldStarred:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field starred", values[i])
			} else if value.Valid {
				_m.Starred = value.Bool
			}
		case entry.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case entry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Entry.
// This includes values selected through modifiers, order, etc.
func (_m *Entry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Entry.
// Note that you need to call Entry.Unwrap() before calling this method if this Entry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Entry) Update() *EntryUpdateOne {
	return NewEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Entry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Entry) Unwrap() *Entry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Entry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Entry) String() string {
	var builder strings.Builder
	builder.WriteString("Entry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tool=")
	builder.WriteString(_m.Tool)
	builder.WriteString(", ")
	builder.WriteString("tool_version=")
	builder.WriteString(_m.ToolVersion)
	builder.WriteString(", ")
	builder.WriteString("cwd=")
	builder.WriteString(_m.Cwd)
	builder.WriteString(", ")
	builder.WriteString("project=")
	builder.WriteString(_m.Project)
	builder.WriteString(", ")
	builder.WriteString("repo_owner=")
	builder.WriteString(_m.RepoOwner)
	builder.WriteString(", ")
	builder.WriteString("repo_name=")
	builder.WriteString(_m.RepoName)
	builder.WriteString(", ")
	builder.WriteString("repo_remote=")
	builder.WriteString(_m.RepoRemote)
	builder.WriteString(", ")
	builder.WriteString("git_branch=")
	builder.WriteString(_m.GitBranch)
	builder.WriteString(", ")
	builder.WriteString("git_commit=")
	builder.WriteString(_m.GitCommit)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("session_name=")
	builder.WriteString(_m.SessionName)
	builder.WriteString(", ")
	builder.WriteString("turn_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.TurnIndex))
	builder.WriteString(", ")
	builder.WriteString("parent_entry_id=")
	builder.WriteString(_m.ParentEntryID)
	builder.WriteString(", ")
	builder.WriteString("hostname=")
	builder.WriteString(_m.Hostname)
	builder.WriteString(", ")
	builder.WriteString("user=")
	builder.WriteString(_m.User)
	builder.WriteString(", ")
	builder.WriteString("shell=")
	builder.WriteString(_m.Shell)
	builder.WriteString(", ")
	builder.WriteString("terminal=")
	builder.WriteString(_m.Terminal)
	builder.WriteString(", ")
	builder.WriteString("terminal_title=")
	builder.WriteString(_m.TerminalTitle)
	builder.WriteString(", ")
	builder.WriteString("tty=")
	builder.WriteString(_m.Tty)
	builder.WriteString(", ")
	builder.WriteString("pid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pid))
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("response=")
	builder.WriteString(_m.Response)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("raw=")
	builder.WriteString(_m.Raw)
	builder.WriteString(", ")
	builder.WriteString("token_count_in=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenCountIn))
	builder.WriteString(", ")
	builder.WriteString("token_count_out=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenCountOut))
	builder.WriteString(", ")
	builder.WriteString("token_count_cache_read=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenCountCacheRead))
	builder.WriteString(", ")
	builder.WriteString("token_count_cache_create=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenCountCacheCreate))
	builder.WriteString(", ")
	builder.WriteString("stop_reason=")
	builder.WriteString(_m.StopReason)
	builder.WriteString(", ")
	builder.WriteString("permission_mode=")
	builder.WriteString(_m.PermissionMode)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(_m.Tags)
	builder.WriteString(", ")
	builder.WriteString("starred=")
	builder.WriteString(fmt.Sprintf("%v", _m.Starred))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Entries is a parsable slice of Entry.
type Entries []*Entry
