// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/ai-logger/ent/entry"
	"github.com/khanakia/ai-logger/ent/predicate"
)

// EntryUpdate is the builder for updating Entry entities.
type EntryUpdate struct {
	config
	hooks    []Hook
	mutation *EntryMutation
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdate) Where(ps ...predicate.Entry) *EntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTool sets the "tool" field.
func (_u *EntryUpdate) SetTool(v string) *EntryUpdate {
	_u.mutation.SetTool(v)
	return _u
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTool(v *string) *EntryUpdate {
	if v != nil {
		_u.SetTool(*v)
	}
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *EntryUpdate) SetCwd(v string) *EntryUpdate {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableCwd(v *string) *EntryUpdate {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *EntryUpdate) SetProject(v string) *EntryUpdate {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableProject(v *string) *EntryUpdate {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// SetRepoOwner sets the "repo_owner" field.
func (_u *EntryUpdate) SetRepoOwner(v string) *EntryUpdate {
	_u.mutation.SetRepoOwner(v)
	return _u
}

// SetNillableRepoOwner sets the "repo_owner" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableRepoOwner(v *string) *EntryUpdate {
	if v != nil {
		_u.SetRepoOwner(*v)
	}
	return _u
}

// SetRepoName sets the "repo_name" field.
func (_u *EntryUpdate) SetRepoName(v string) *EntryUpdate {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableRepoName(v *string) *EntryUpdate {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetRepoRemote sets the "repo_remote" field.
func (_u *EntryUpdate) SetRepoRemote(v string) *EntryUpdate {
	_u.mutation.SetRepoRemote(v)
	return _u
}

// SetNillableRepoRemote sets the "repo_remote" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableRepoRemote(v *string) *EntryUpdate {
	if v != nil {
		_u.SetRepoRemote(*v)
	}
	return _u
}

// SetGitBranch sets the "git_branch" field.
func (_u *EntryUpdate) SetGitBranch(v string) *EntryUpdate {
	_u.mutation.SetGitBranch(v)
	return _u
}

// SetNillableGitBranch sets the "git_branch" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableGitBranch(v *string) *EntryUpdate {
	if v != nil {
		_u.SetGitBranch(*v)
	}
	return _u
}

// SetGitCommit sets the "git_commit" field.
func (_u *EntryUpdate) SetGitCommit(v string) *EntryUpdate {
	_u.mutation.SetGitCommit(v)
	return _u
}

// SetNillableGitCommit sets the "git_commit" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableGitCommit(v *string) *EntryUpdate {
	if v != nil {
		_u.SetGitCommit(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *EntryUpdate) SetSessionID(v string) *EntryUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableSessionID(v *string) *EntryUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSessionName sets the "session_name" field.
func (_u *EntryUpdate) SetSessionName(v string) *EntryUpdate {
	_u.mutation.SetSessionName(v)
	return _u
}

// SetNillableSessionName sets the "session_name" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableSessionName(v *string) *EntryUpdate {
	if v != nil {
		_u.SetSessionName(*v)
	}
	return _u
}

// SetTurnIndex sets the "turn_index" field.
func (_u *EntryUpdate) SetTurnIndex(v int) *EntryUpdate {
	_u.mutation.ResetTurnIndex()
	_u.mutation.SetTurnIndex(v)
	return _u
}

// SetNillableTurnIndex sets the "turn_index" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTurnIndex(v *int) *EntryUpdate {
	if v != nil {
		_u.SetTurnIndex(*v)
	}
	return _u
}

// AddTurnIndex adds value to the "turn_index" field.
func (_u *EntryUpdate) AddTurnIndex(v int) *EntryUpdate {
	_u.mutation.AddTurnIndex(v)
	return _u
}

// SetParentEntryID sets the "parent_entry_id" field.
func (_u *EntryUpdate) SetParentEntryID(v string) *EntryUpdate {
	_u.mutation.SetParentEntryID(v)
	return _u
}

// SetNillableParentEntryID sets the "parent_entry_id" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableParentEntryID(v *string) *EntryUpdate {
	if v != nil {
		_u.SetParentEntryID(*v)
	}
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *EntryUpdate) SetHostname(v string) *EntryUpdate {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableHostname(v *string) *EntryUpdate {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetUser sets the "user" field.
func (_u *EntryUpdate) SetUser(v string) *EntryUpdate {
	_u.mutation.SetUser(v)
	return _u
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableUser(v *string) *EntryUpdate {
	if v != nil {
		_u.SetUser(*v)
	}
	return _u
}

// SetShell sets the "shell" field.
func (_u *EntryUpdate) SetShell(v string) *EntryUpdate {
	_u.mutation.SetShell(v)
	return _u
}

// SetNillableShell sets the "shell" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableShell(v *string) *EntryUpdate {
	if v != nil {
		_u.SetShell(*v)
	}
	return _u
}

// SetTerminal sets the "terminal" field.
func (_u *EntryUpdate) SetTerminal(v string) *EntryUpdate {
	_u.mutation.SetTerminal(v)
	return _u
}

// SetNillableTerminal sets the "terminal" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTerminal(v *string) *EntryUpdate {
	if v != nil {
		_u.SetTerminal(*v)
	}
	return _u
}

// SetTerminalTitle sets the "terminal_title" field.
func (_u *EntryUpdate) SetTerminalTitle(v string) *EntryUpdate {
	_u.mutation.SetTerminalTitle(v)
	return _u
}

// SetNillableTerminalTitle sets the "terminal_title" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTerminalTitle(v *string) *EntryUpdate {
	if v != nil {
		_u.SetTerminalTitle(*v)
	}
	return _u
}

// SetTty sets the "tty" field.
func (_u *EntryUpdate) SetTty(v string) *EntryUpdate {
	_u.mutation.SetTty(v)
	return _u
}

// SetNillableTty sets the "tty" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTty(v *string) *EntryUpdate {
	if v != nil {
		_u.SetTty(*v)
	}
	return _u
}

// SetPid sets the "pid" field.
func (_u *EntryUpdate) SetPid(v int) *EntryUpdate {
	_u.mutation.ResetPid()
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *EntryUpdate) SetNillablePid(v *int) *EntryUpdate {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// AddPid adds value to the "pid" field.
func (_u *EntryUpdate) AddPid(v int) *EntryUpdate {
	_u.mutation.AddPid(v)
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *EntryUpdate) SetPrompt(v string) *EntryUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *EntryUpdate) SetNillablePrompt(v *string) *EntryUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetResponse sets the "response" field.
func (_u *EntryUpdate) SetResponse(v string) *EntryUpdate {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableResponse(v *string) *EntryUpdate {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *EntryUpdate) SetModel(v string) *EntryUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableModel(v *string) *EntryUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRaw sets the "raw" field.
func (_u *EntryUpdate) SetRaw(v string) *EntryUpdate {
	_u.mutation.SetRaw(v)
	return _u
}

// SetNillableRaw sets the "raw" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableRaw(v *string) *EntryUpdate {
	if v != nil {
		_u.SetRaw(*v)
	}
	return _u
}

// SetTokenCountIn sets the "token_count_in" field.
func (_u *EntryUpdate) SetTokenCountIn(v int) *EntryUpdate {
	_u.mutation.ResetTokenCountIn()
	_u.mutation.SetTokenCountIn(v)
	return _u
}

// SetNillableTokenCountIn sets the "token_count_in" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTokenCountIn(v *int) *EntryUpdate {
	if v != nil {
		_u.SetTokenCountIn(*v)
	}
	return _u
}

// AddTokenCountIn adds value to the "token_count_in" field.
func (_u *EntryUpdate) AddTokenCountIn(v int) *EntryUpdate {
	_u.mutation.AddTokenCountIn(v)
	return _u
}

// SetTokenCountOut sets the "token_count_out" field.
func (_u *EntryUpdate) SetTokenCountOut(v int) *EntryUpdate {
	_u.mutation.ResetTokenCountOut()
	_u.mutation.SetTokenCountOut(v)
	return _u
}

// SetNillableTokenCountOut sets the "token_count_out" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTokenCountOut(v *int) *EntryUpdate {
	if v != nil {
		_u.SetTokenCountOut(*v)
	}
	return _u
}

// AddTokenCountOut adds value to the "token_count_out" field.
func (_u *EntryUpdate) AddTokenCountOut(v int) *EntryUpdate {
	_u.mutation.AddTokenCountOut(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *EntryUpdate) SetTags(v string) *EntryUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableTags(v *string) *EntryUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// SetStarred sets the "starred" field.
func (_u *EntryUpdate) SetStarred(v bool) *EntryUpdate {
	_u.mutation.SetStarred(v)
	return _u
}

// SetNillableStarred sets the "starred" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableStarred(v *bool) *EntryUpdate {
	if v != nil {
		_u.SetStarred(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EntryUpdate) SetNotes(v string) *EntryUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableNotes(v *string) *EntryUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdate) Mutation() *EntryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tool(); ok {
		_spec.SetField(entry.FieldTool, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(entry.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(entry.FieldProject, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoOwner(); ok {
		_spec.SetField(entry.FieldRepoOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(entry.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoRemote(); ok {
		_spec.SetField(entry.FieldRepoRemote, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitBranch(); ok {
		_spec.SetField(entry.FieldGitBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitCommit(); ok {
		_spec.SetField(entry.FieldGitCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(entry.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionName(); ok {
		_spec.SetField(entry.FieldSessionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TurnIndex(); ok {
		_spec.SetField(entry.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTurnIndex(); ok {
		_spec.AddField(entry.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParentEntryID(); ok {
		_spec.SetField(entry.FieldParentEntryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(entry.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.User(); ok {
		_spec.SetField(entry.FieldUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shell(); ok {
		_spec.SetField(entry.FieldShell, field.TypeString, value)
	}
	if value, ok := _u.mutation.Terminal(); ok {
		_spec.SetField(entry.FieldTerminal, field.TypeString, value)
	}
	if value, ok := _u.mutation.TerminalTitle(); ok {
		_spec.SetField(entry.FieldTerminalTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tty(); ok {
		_spec.SetField(entry.FieldTty, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(entry.FieldPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPid(); ok {
		_spec.AddField(entry.FieldPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(entry.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(entry.FieldResponse, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(entry.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(entry.FieldRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenCountIn(); ok {
		_spec.SetField(entry.FieldTokenCountIn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCountIn(); ok {
		_spec.AddField(entry.FieldTokenCountIn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TokenCountOut(); ok {
		_spec.SetField(entry.FieldTokenCountOut, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCountOut(); ok {
		_spec.AddField(entry.FieldTokenCountOut, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(entry.FieldTags, field.TypeString, value)
	}
	if value, ok := _u.mutation.Starred(); ok {
		_spec.SetField(entry.FieldStarred, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(entry.FieldNotes, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntryUpdateOne is the builder for updating a single Entry entity.
type EntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntryMutation
}

// SetTool sets the "tool" field.
func (_u *EntryUpdateOne) SetTool(v string) *EntryUpdateOne {
	_u.mutation.SetTool(v)
	return _u
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTool(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetTool(*v)
	}
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *EntryUpdateOne) SetCwd(v string) *EntryUpdateOne {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableCwd(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *EntryUpdateOne) SetProject(v string) *EntryUpdateOne {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableProject(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// SetRepoOwner sets the "repo_owner" field.
func (_u *EntryUpdateOne) SetRepoOwner(v string) *EntryUpdateOne {
	_u.mutation.SetRepoOwner(v)
	return _u
}

// SetNillableRepoOwner sets the "repo_owner" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableRepoOwner(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetRepoOwner(*v)
	}
	return _u
}

// SetRepoName sets the "repo_name" field.
func (_u *EntryUpdateOne) SetRepoName(v string) *EntryUpdateOne {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableRepoName(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetRepoRemote sets the "repo_remote" field.
func (_u *EntryUpdateOne) SetRepoRemote(v string) *EntryUpdateOne {
	_u.mutation.SetRepoRemote(v)
	return _u
}

// SetNillableRepoRemote sets the "repo_remote" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableRepoRemote(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetRepoRemote(*v)
	}
	return _u
}

// SetGitBranch sets the "git_branch" field.
func (_u *EntryUpdateOne) SetGitBranch(v string) *EntryUpdateOne {
	_u.mutation.SetGitBranch(v)
	return _u
}

// SetNillableGitBranch sets the "git_branch" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableGitBranch(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetGitBranch(*v)
	}
	return _u
}

// SetGitCommit sets the "git_commit" field.
func (_u *EntryUpdateOne) SetGitCommit(v string) *EntryUpdateOne {
	_u.mutation.SetGitCommit(v)
	return _u
}

// SetNillableGitCommit sets the "git_commit" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableGitCommit(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetGitCommit(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *EntryUpdateOne) SetSessionID(v string) *EntryUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableSessionID(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSessionName sets the "session_name" field.
func (_u *EntryUpdateOne) SetSessionName(v string) *EntryUpdateOne {
	_u.mutation.SetSessionName(v)
	return _u
}

// SetNillableSessionName sets the "session_name" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableSessionName(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetSessionName(*v)
	}
	return _u
}

// SetTurnIndex sets the "turn_index" field.
func (_u *EntryUpdateOne) SetTurnIndex(v int) *EntryUpdateOne {
	_u.mutation.ResetTurnIndex()
	_u.mutation.SetTurnIndex(v)
	return _u
}

// SetNillableTurnIndex sets the "turn_index" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTurnIndex(v *int) *EntryUpdateOne {
	if v != nil {
		_u.SetTurnIndex(*v)
	}
	return _u
}

// AddTurnIndex adds value to the "turn_index" field.
func (_u *EntryUpdateOne) AddTurnIndex(v int) *EntryUpdateOne {
	_u.mutation.AddTurnIndex(v)
	return _u
}

// SetParentEntryID sets the "parent_entry_id" field.
func (_u *EntryUpdateOne) SetParentEntryID(v string) *EntryUpdateOne {
	_u.mutation.SetParentEntryID(v)
	return _u
}

// SetNillableParentEntryID sets the "parent_entry_id" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableParentEntryID(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetParentEntryID(*v)
	}
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *EntryUpdateOne) SetHostname(v string) *EntryUpdateOne {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableHostname(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetUser sets the "user" field.
func (_u *EntryUpdateOne) SetUser(v string) *EntryUpdateOne {
	_u.mutation.SetUser(v)
	return _u
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableUser(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetUser(*v)
	}
	return _u
}

// SetShell sets the "shell" field.
func (_u *EntryUpdateOne) SetShell(v string) *EntryUpdateOne {
	_u.mutation.SetShell(v)
	return _u
}

// SetNillableShell sets the "shell" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableShell(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetShell(*v)
	}
	return _u
}

// SetTerminal sets the "terminal" field.
func (_u *EntryUpdateOne) SetTerminal(v string) *EntryUpdateOne {
	_u.mutation.SetTerminal(v)
	return _u
}

// SetNillableTerminal sets the "terminal" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTerminal(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetTerminal(*v)
	}
	return _u
}

// SetTerminalTitle sets the "terminal_title" field.
func (_u *EntryUpdateOne) SetTerminalTitle(v string) *EntryUpdateOne {
	_u.mutation.SetTerminalTitle(v)
	return _u
}

// SetNillableTerminalTitle sets the "terminal_title" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTerminalTitle(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetTerminalTitle(*v)
	}
	return _u
}

// SetTty sets the "tty" field.
func (_u *EntryUpdateOne) SetTty(v string) *EntryUpdateOne {
	_u.mutation.SetTty(v)
	return _u
}

// SetNillableTty sets the "tty" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTty(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetTty(*v)
	}
	return _u
}

// SetPid sets the "pid" field.
func (_u *EntryUpdateOne) SetPid(v int) *EntryUpdateOne {
	_u.mutation.ResetPid()
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillablePid(v *int) *EntryUpdateOne {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// AddPid adds value to the "pid" field.
func (_u *EntryUpdateOne) AddPid(v int) *EntryUpdateOne {
	_u.mutation.AddPid(v)
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *EntryUpdateOne) SetPrompt(v string) *EntryUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillablePrompt(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetResponse sets the "response" field.
func (_u *EntryUpdateOne) SetResponse(v string) *EntryUpdateOne {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableResponse(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *EntryUpdateOne) SetModel(v string) *EntryUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableModel(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRaw sets the "raw" field.
func (_u *EntryUpdateOne) SetRaw(v string) *EntryUpdateOne {
	_u.mutation.SetRaw(v)
	return _u
}

// SetNillableRaw sets the "raw" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableRaw(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetRaw(*v)
	}
	return _u
}

// SetTokenCountIn sets the "token_count_in" field.
func (_u *EntryUpdateOne) SetTokenCountIn(v int) *EntryUpdateOne {
	_u.mutation.ResetTokenCountIn()
	_u.mutation.SetTokenCountIn(v)
	return _u
}

// SetNillableTokenCountIn sets the "token_count_in" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTokenCountIn(v *int) *EntryUpdateOne {
	if v != nil {
		_u.SetTokenCountIn(*v)
	}
	return _u
}

// AddTokenCountIn adds value to the "token_count_in" field.
func (_u *EntryUpdateOne) AddTokenCountIn(v int) *EntryUpdateOne {
	_u.mutation.AddTokenCountIn(v)
	return _u
}

// SetTokenCountOut sets the "token_count_out" field.
func (_u *EntryUpdateOne) SetTokenCountOut(v int) *EntryUpdateOne {
	_u.mutation.ResetTokenCountOut()
	_u.mutation.SetTokenCountOut(v)
	return _u
}

// SetNillableTokenCountOut sets the "token_count_out" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTokenCountOut(v *int) *EntryUpdateOne {
	if v != nil {
		_u.SetTokenCountOut(*v)
	}
	return _u
}

// AddTokenCountOut adds value to the "token_count_out" field.
func (_u *EntryUpdateOne) AddTokenCountOut(v int) *EntryUpdateOne {
	_u.mutation.AddTokenCountOut(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *EntryUpdateOne) SetTags(v string) *EntryUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableTags(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// SetStarred sets the "starred" field.
func (_u *EntryUpdateOne) SetStarred(v bool) *EntryUpdateOne {
	_u.mutation.SetStarred(v)
	return _u
}

// SetNillableStarred sets the "starred" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableStarred(v *bool) *EntryUpdateOne {
	if v != nil {
		_u.SetStarred(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EntryUpdateOne) SetNotes(v string) *EntryUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableNotes(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdateOne) Mutation() *EntryMutation {
	return _u.mutation
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdateOne) Where(ps ...predicate.Entry) *EntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntryUpdateOne) Select(field string, fields ...string) *EntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Entry entity.
func (_u *EntryUpdateOne) Save(ctx context.Context) (*Entry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdateOne) SaveX(ctx context.Context) *Entry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EntryUpdateOne) sqlSave(ctx context.Context) (_node *Entry, err error) {
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entry.FieldID)
		for _, f := range fields {
			if !entry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tool(); ok {
		_spec.SetField(entry.FieldTool, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(entry.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(entry.FieldProject, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoOwner(); ok {
		_spec.SetField(entry.FieldRepoOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(entry.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoRemote(); ok {
		_spec.SetField(entry.FieldRepoRemote, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitBranch(); ok {
		_spec.SetField(entry.FieldGitBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitCommit(); ok {
		_spec.SetField(entry.FieldGitCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(entry.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionName(); ok {
		_spec.SetField(entry.FieldSessionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TurnIndex(); ok {
		_spec.SetField(entry.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTurnIndex(); ok {
		_spec.AddField(entry.FieldTurnIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ParentEntryID(); ok {
		_spec.SetField(entry.FieldParentEntryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(entry.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.User(); ok {
		_spec.SetField(entry.FieldUser, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shell(); ok {
		_spec.SetField(entry.FieldShell, field.TypeString, value)
	}
	if value, ok := _u.mutation.Terminal(); ok {
		_spec.SetField(entry.FieldTerminal, field.TypeString, value)
	}
	if value, ok := _u.mutation.TerminalTitle(); ok {
		_spec.SetField(entry.FieldTerminalTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tty(); ok {
		_spec.SetField(entry.FieldTty, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(entry.FieldPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPid(); ok {
		_spec.AddField(entry.FieldPid, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(entry.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(entry.FieldResponse, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(entry.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(entry.FieldRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenCountIn(); ok {
		_spec.SetField(entry.FieldTokenCountIn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCountIn(); ok {
		_spec.AddField(entry.FieldTokenCountIn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TokenCountOut(); ok {
		_spec.SetField(entry.FieldTokenCountOut, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenCountOut(); ok {
		_spec.AddField(entry.FieldTokenCountOut, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(entry.FieldTags, field.TypeString, value)
	}
	if value, ok := _u.mutation.Starred(); ok {
		_spec.SetField(entry.FieldStarred, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(entry.FieldNotes, field.TypeString, value)
	}
	_node = &Entry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
