// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/ai-logger/ent/session"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetTool sets the "tool" field.
func (_c *SessionCreate) SetTool(v string) *SessionCreate {
	_c.mutation.SetTool(v)
	return _c
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (_c *SessionCreate) SetNillableTool(v *string) *SessionCreate {
	if v != nil {
		_c.SetTool(*v)
	}
	return _c
}

// SetProject sets the "project" field.
func (_c *SessionCreate) SetProject(v string) *SessionCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_c *SessionCreate) SetNillableProject(v *string) *SessionCreate {
	if v != nil {
		_c.SetProject(*v)
	}
	return _c
}

// SetSessionName sets the "session_name" field.
func (_c *SessionCreate) SetSessionName(v string) *SessionCreate {
	_c.mutation.SetSessionName(v)
	return _c
}

// SetNillableSessionName sets the "session_name" field if the given value is not nil.
func (_c *SessionCreate) SetNillableSessionName(v *string) *SessionCreate {
	if v != nil {
		_c.SetSessionName(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SessionCreate) SetStartedAt(v time.Time) *SessionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableStartedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *SessionCreate) SetEndedAt(v time.Time) *SessionCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableEndedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetEntryCount sets the "entry_count" field.
func (_c *SessionCreate) SetEntryCount(v int) *SessionCreate {
	_c.mutation.SetEntryCount(v)
	return _c
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_c *SessionCreate) SetNillableEntryCount(v *int) *SessionCreate {
	if v != nil {
		_c.SetEntryCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionCreate) SetID(v string) *SessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionCreate) defaults() {
	if _, ok := _c.mutation.Tool(); !ok {
		v := session.DefaultTool
		_c.mutation.SetTool(v)
	}
	if _, ok := _c.mutation.Project(); !ok {
		v := session.DefaultProject
		_c.mutation.SetProject(v)
	}
	if _, ok := _c.mutation.SessionName(); !ok {
		v := session.DefaultSessionName
		_c.mutation.SetSessionName(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := session.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.EntryCount(); !ok {
		v := session.DefaultEntryCount
		_c.mutation.SetEntryCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.Tool(); !ok {
		return &ValidationError{Name: "tool", err: errors.New(`ent: missing required field "Session.tool"`)}
	}
	if _, ok := _c.mutation.Project(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required field "Session.project"`)}
	}
	if _, ok := _c.mutation.SessionName(); !ok {
		return &ValidationError{Name: "session_name", err: errors.New(`ent: missing required field "Session.session_name"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Session.started_at"`)}
	}
	if _, ok := _c.mutation.EntryCount(); !ok {
		return &ValidationError{Name: "entry_count", err: errors.New(`ent: missing required field "Session.entry_count"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := session.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Session.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Session.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Tool(); ok {
		_spec.SetField(session.FieldTool, field.TypeString, value)
		_node.Tool = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(session.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.SessionName(); ok {
		_spec.SetField(session.FieldSessionName, field.TypeString, value)
		_node.SessionName = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(session.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.EntryCount(); ok {
		_spec.SetField(session.FieldEntryCount, field.TypeInt, value)
		_node.EntryCount = value
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
