// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khanakia/ai-logger/ent/predicate"
	"github.com/khanakia/ai-logger/ent/session"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTool sets the "tool" field.
func (_u *SessionUpdate) SetTool(v string) *SessionUpdate {
	_u.mutation.SetTool(v)
	return _u
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableTool(v *string) *SessionUpdate {
	if v != nil {
		_u.SetTool(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *SessionUpdate) SetProject(v string) *SessionUpdate {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableProject(v *string) *SessionUpdate {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// SetSessionName sets the "session_name" field.
func (_u *SessionUpdate) SetSessionName(v string) *SessionUpdate {
	_u.mutation.SetSessionName(v)
	return _u
}

// SetNillableSessionName sets the "session_name" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableSessionName(v *string) *SessionUpdate {
	if v != nil {
		_u.SetSessionName(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdate) SetEndedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEndedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdate) ClearEndedAt() *SessionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetEntryCount sets the "entry_count" field.
func (_u *SessionUpdate) SetEntryCount(v int) *SessionUpdate {
	_u.mutation.ResetEntryCount()
	_u.mutation.SetEntryCount(v)
	return _u
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEntryCount(v *int) *SessionUpdate {
	if v != nil {
		_u.SetEntryCount(*v)
	}
	return _u
}

// AddEntryCount adds value to the "entry_count" field.
func (_u *SessionUpdate) AddEntryCount(v int) *SessionUpdate {
	_u.mutation.AddEntryCount(v)
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tool(); ok {
		_spec.SetField(session.FieldTool, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(session.FieldProject, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionName(); ok {
		_spec.SetField(session.FieldSessionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EntryCount(); ok {
		_spec.SetField(session.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntryCount(); ok {
		_spec.AddField(session.FieldEntryCount, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetTool sets the "tool" field.
func (_u *SessionUpdateOne) SetTool(v string) *SessionUpdateOne {
	_u.mutation.SetTool(v)
	return _u
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableTool(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetTool(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *SessionUpdateOne) SetProject(v string) *SessionUpdateOne {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableProject(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// SetSessionName sets the "session_name" field.
func (_u *SessionUpdateOne) SetSessionName(v string) *SessionUpdateOne {
	_u.mutation.SetSessionName(v)
	return _u
}

// SetNillableSessionName sets the "session_name" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableSessionName(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetSessionName(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdateOne) SetEndedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEndedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdateOne) ClearEndedAt() *SessionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetEntryCount sets the "entry_count" field.
func (_u *SessionUpdateOne) SetEntryCount(v int) *SessionUpdateOne {
	_u.mutation.ResetEntryCount()
	_u.mutation.SetEntryCount(v)
	return _u
}

// SetNillableEntryCount sets the "entry_count" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEntryCount(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetEntryCount(*v)
	}
	return _u
}

// AddEntryCount adds value to the "entry_count" field.
func (_u *SessionUpdateOne) AddEntryCount(v int) *SessionUpdateOne {
	_u.mutation.AddEntryCount(v)
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tool(); ok {
		_spec.SetField(session.FieldTool, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(session.FieldProject, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionName(); ok {
		_spec.SetField(session.FieldSessionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EntryCount(); ok {
		_spec.SetField(session.FieldEntryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntryCount(); ok {
		_spec.AddField(session.FieldEntryCount, field.TypeInt, value)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
