// Code generated by ent, DO NOT EDIT.

package entry

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the entry type in the database.
	Label = "entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTool holds the string denoting the tool field in the database.
	FieldTool = "tool"
	// FieldToolVersion holds the string denoting the tool_version field in the database.
	FieldToolVersion = "tool_version"
	// FieldCwd holds the string denoting the cwd field in the database.
	FieldCwd = "cwd"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldRepoOwner holds the string denoting the repo_owner field in the database.
	FieldRepoOwner = "repo_owner"
	// FieldRepoName holds the string denoting the repo_name field in the database.
	FieldRepoName = "repo_name"
	// FieldRepoRemote holds the string denoting the repo_remote field in the database.
	FieldRepoRemote = "repo_remote"
	// FieldGitBranch holds the string denoting the git_branch field in the database.
	FieldGitBranch = "git_branch"
	// FieldGitCommit holds the string denoting the git_commit field in the database.
	FieldGitCommit = "git_commit"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldSessionName holds the string denoting the session_name field in the database.
	FieldSessionName = "session_name"
	// FieldTurnIndex holds the string denoting the turn_index field in the database.
	FieldTurnIndex = "turn_index"
	// FieldParentEntryID holds the string denoting the parent_entry_id field in the database.
	FieldParentEntryID = "parent_entry_id"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldShell holds the string denoting the shell field in the database.
	FieldShell = "shell"
	// FieldTerminal holds the string denoting the terminal field in the database.
	FieldTerminal = "terminal"
	// FieldTerminalTitle holds the string denoting the terminal_title field in the database.
	FieldTerminalTitle = "terminal_title"
	// FieldTty holds the string denoting the tty field in the database.
	FieldTty = "tty"
	// FieldPid holds the string denoting the pid field in the database.
	FieldPid = "pid"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldResponse holds the string denoting the response field in the database.
	FieldResponse = "response"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRaw holds the string denoting the raw field in the database.
	FieldRaw = "raw"
	// FieldTokenCountIn holds the string denoting the token_count_in field in the database.
	FieldTokenCountIn = "token_count_in"
	// FieldTokenCountOut holds the string denoting the token_count_out field in the database.
	FieldTokenCountOut = "token_count_out"
	// FieldTokenCountCacheRead holds the string denoting the token_count_cache_read field in the database.
	FieldTokenCountCacheRead = "token_count_cache_read"
	// FieldTokenCountCacheCreate holds the string denoting the token_count_cache_create field in the database.
	FieldTokenCountCacheCreate = "token_count_cache_create"
	// FieldStopReason holds the string denoting the stop_reason field in the database.
	FieldStopReason = "stop_reason"
	// FieldPermissionMode holds the string denoting the permission_mode field in the database.
	FieldPermissionMode = "permission_mode"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldStarred holds the string denoting the starred field in the database.
	FieldStarred = "starred"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the entry in the database.
	Table = "entries"
)

// Columns holds all SQL columns for entry fields.
var Columns = []string{
	FieldID,
	FieldTool,
	FieldToolVersion,
	FieldCwd,
	FieldProject,
	FieldRepoOwner,
	FieldRepoName,
	FieldRepoRemote,
	FieldGitBranch,
	FieldGitCommit,
	FieldSessionID,
	FieldSessionName,
	FieldTurnIndex,
	FieldParentEntryID,
	FieldHostname,
	FieldUser,
	FieldShell,
	FieldTerminal,
	FieldTerminalTitle,
	FieldTty,
	FieldPid,
	FieldPrompt,
	FieldResponse,
	FieldModel,
	FieldRaw,
	FieldTokenCountIn,
	FieldTokenCountOut,
	FieldTokenCountCacheRead,
	FieldTokenCountCacheCreate,
	FieldStopReason,
	FieldPermissionMode,
	FieldTags,
	FieldStarred,
	FieldNotes,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTool holds the default value on creation for the "tool" field.
	DefaultTool string
	// DefaultToolVersion holds the default value on creation for the "tool_version" field.
	DefaultToolVersion string
	// DefaultCwd holds the default value on creation for the "cwd" field.
	DefaultCwd string
	// DefaultProject holds the default value on creation for the "project" field.
	DefaultProject string
	// DefaultRepoOwner holds the default value on creation for the "repo_owner" field.
	DefaultRepoOwner string
	// DefaultRepoName holds the default value on creation for the "repo_name" field.
	DefaultRepoName string
	// DefaultRepoRemote holds the default value on creation for the "repo_remote" field.
	DefaultRepoRemote string
	// DefaultGitBranch holds the default value on creation for the "git_branch" field.
	DefaultGitBranch string
	// DefaultGitCommit holds the default value on creation for the "git_commit" field.
	DefaultGitCommit string
	// DefaultSessionID holds the default value on creation for the "session_id" field.
	DefaultSessionID string
	// DefaultSessionName holds the default value on creation for the "session_name" field.
	DefaultSessionName string
	// DefaultTurnIndex holds the default value on creation for the "turn_index" field.
	DefaultTurnIndex int
	// DefaultParentEntryID holds the default value on creation for the "parent_entry_id" field.
	DefaultParentEntryID string
	// DefaultHostname holds the default value on creation for the "hostname" field.
	DefaultHostname string
	// DefaultUser holds the default value on creation for the "user" field.
	DefaultUser string
	// DefaultShell holds the default value on creation for the "shell" field.
	DefaultShell string
	// DefaultTerminal holds the default value on creation for the "terminal" field.
	DefaultTerminal string
	// DefaultTerminalTitle holds the default value on creation for the "terminal_title" field.
	DefaultTerminalTitle string
	// DefaultTty holds the default value on creation for the "tty" field.
	DefaultTty string
	// DefaultPid holds the default value on creation for the "pid" field.
	DefaultPid int
	// DefaultPrompt holds the default value on creation for the "prompt" field.
	DefaultPrompt string
	// DefaultResponse holds the default value on creation for the "response" field.
	DefaultResponse string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultRaw holds the default value on creation for the "raw" field.
	DefaultRaw string
	// DefaultTokenCountIn holds the default value on creation for the "token_count_in" field.
	DefaultTokenCountIn int
	// DefaultTokenCountOut holds the default value on creation for the "token_count_out" field.
	DefaultTokenCountOut int
	// DefaultTokenCountCacheRead holds the default value on creation for the "token_count_cache_read" field.
	DefaultTokenCountCacheRead int
	// DefaultTokenCountCacheCreate holds the default value on creation for the "token_count_cache_create" field.
	DefaultTokenCountCacheCreate int
	// DefaultStopReason holds the default value on creation for the "stop_reason" field.
	DefaultStopReason string
	// DefaultPermissionMode holds the default value on creation for the "permission_mode" field.
	DefaultPermissionMode string
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags string
	// DefaultStarred holds the default value on creation for the "starred" field.
	DefaultStarred bool
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Entry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTool orders the results by the tool field.
func ByTool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTool, opts...).ToFunc()
}

// ByToolVersion orders the results by the tool_version field.
func ByToolVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolVersion, opts...).ToFunc()
}

// ByCwd orders the results by the cwd field.
func ByCwd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCwd, opts...).ToFunc()
}

// ByProject orders the results by the project field.
func ByProject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProject, opts...).ToFunc()
}

// ByRepoOwner orders the results by the repo_owner field.
func ByRepoOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoOwner, opts...).ToFunc()
}

// ByRepoName orders the results by the repo_name field.
func ByRepoName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoName, opts...).ToFunc()
}

// ByRepoRemote orders the results by the repo_remote field.
func ByRepoRemote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoRemote, opts...).ToFunc()
}

// ByGitBranch orders the results by the git_branch field.
func ByGitBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGitBranch, opts...).ToFunc()
}

// ByGitCommit orders the results by the git_commit field.
func ByGitCommit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGitCommit, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// BySessionName orders the results by the session_name field.
func BySessionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionName, opts...).ToFunc()
}

// ByTurnIndex orders the results by the turn_index field.
func ByTurnIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnIndex, opts...).ToFunc()
}

// ByParentEntryID orders the results by the parent_entry_id field.
func ByParentEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentEntryID, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByUser orders the results by the user field.
func ByUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUser, opts...).ToFunc()
}

// ByShell orders the results by the shell field.
func ByShell(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShell, opts...).ToFunc()
}

// ByTerminal orders the results by the terminal field.
func ByTerminal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTerminal, opts...).ToFunc()
}

// ByTerminalTitle orders the results by the terminal_title field.
func ByTerminalTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTerminalTitle, opts...).ToFunc()
}

// ByTty orders the results by the tty field.
func ByTty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTty, opts...).ToFunc()
}

// ByPid orders the results by the pid field.
func ByPid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPid, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByResponse orders the results by the response field.
func ByResponse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponse, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByRaw orders the results by the raw field.
func ByRaw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRaw, opts...).ToFunc()
}

// ByTokenCountIn orders the results by the token_count_in field.
func ByTokenCountIn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenCountIn, opts...).ToFunc()
}

// ByTokenCountOut orders the results by the token_count_out field.
func ByTokenCountOut(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenCountOut, opts...).ToFunc()
}

// ByTokenCountCacheRead orders the results by the token_count_cache_read field.
func ByTokenCountCacheRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenCountCacheRead, opts...).ToFunc()
}

// ByTokenCountCacheCreate orders the results by the token_count_cache_create field.
func ByTokenCountCacheCreate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenCountCacheCreate, opts...).ToFunc()
}

// ByStopReason orders the results by the stop_reason field.
func ByStopReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStopReason, opts...).ToFunc()
}

// ByPermissionMode orders the results by the permission_mode field.
func ByPermissionMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermissionMode, opts...).ToFunc()
}

// ByTags orders the results by the tags field.
func ByTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTags, opts...).ToFunc()
}

// ByStarred orders the results by the starred field.
func ByStarred(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStarred, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
