// Code generated by ent, DO NOT EDIT.

package entry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/khanakia/ai-logger/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldID, id))
}

// Tool applies equality check predicate on the "tool" field. It's identical to ToolEQ.
func Tool(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTool, v))
}

// Cwd applies equality check predicate on the "cwd" field. It's identical to CwdEQ.
func Cwd(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCwd, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldProject, v))
}

// RepoOwner applies equality check predicate on the "repo_owner" field. It's identical to RepoOwnerEQ.
func RepoOwner(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRepoOwner, v))
}

// RepoName applies equality check predicate on the "repo_name" field. It's identical to RepoNameEQ.
func RepoName(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRepoName, v))
}

// RepoRemote applies equality check predicate on the "repo_remote" field. It's identical to RepoRemoteEQ.
func RepoRemote(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRepoRemote, v))
}

// GitBranch applies equality check predicate on the "git_branch" field. It's identical to GitBranchEQ.
func GitBranch(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldGitBranch, v))
}

// GitCommit applies equality check predicate on the "git_commit" field. It's identical to GitCommitEQ.
func GitCommit(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldGitCommit, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldSessionID, v))
}

// SessionName applies equality check predicate on the "session_name" field. It's identical to SessionNameEQ.
func SessionName(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldSessionName, v))
}

// TurnIndex applies equality check predicate on the "turn_index" field. It's identical to TurnIndexEQ.
func TurnIndex(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTurnIndex, v))
}

// ParentEntryID applies equality check predicate on the "parent_entry_id" field. It's identical to ParentEntryIDEQ.
func ParentEntryID(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldParentEntryID, v))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldHostname, v))
}

// User applies equality check predicate on the "user" field. It's identical to UserEQ.
func User(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldUser, v))
}

// Shell applies equality check predicate on the "shell" field. It's identical to ShellEQ.
func Shell(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldShell, v))
}

// Terminal applies equality check predicate on the "terminal" field. It's identical to TerminalEQ.
func Terminal(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTerminal, v))
}

// TerminalTitle applies equality check predicate on the "terminal_title" field. It's identical to TerminalTitleEQ.
func TerminalTitle(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTerminalTitle, v))
}

// Tty applies equality check predicate on the "tty" field. It's identical to TtyEQ.
func Tty(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTty, v))
}

// Pid applies equality check predicate on the "pid" field. It's identical to PidEQ.
func Pid(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPid, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPrompt, v))
}

// Response applies equality check predicate on the "response" field. It's identical to ResponseEQ.
func Response(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldResponse, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldModel, v))
}

// Raw applies equality check predicate on the "raw" field. It's identical to RawEQ.
func Raw(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRaw, v))
}

// TokenCountIn applies equality check predicate on the "token_count_in" field. It's identical to TokenCountInEQ.
func TokenCountIn(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTokenCountIn, v))
}

// TokenCountOut applies equality check predicate on the "token_count_out" field. It's identical to TokenCountOutEQ.
func TokenCountOut(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTokenCountOut, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTags, v))
}

// Starred applies equality check predicate on the "starred" field. It's identical to StarredEQ.
func Starred(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldStarred, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCreatedAt, v))
}

// ToolEQ applies the EQ predicate on the "tool" field.
func ToolEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTool, v))
}

// ToolNEQ applies the NEQ predicate on the "tool" field.
func ToolNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTool, v))
}

// ToolIn applies the In predicate on the "tool" field.
func ToolIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTool, vs...))
}

// ToolNotIn applies the NotIn predicate on the "tool" field.
func ToolNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTool, vs...))
}

// ToolGT applies the GT predicate on the "tool" field.
func ToolGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTool, v))
}

// ToolGTE applies the GTE predicate on the "tool" field.
func ToolGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTool, v))
}

// ToolLT applies the LT predicate on the "tool" field.
func ToolLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTool, v))
}

// ToolLTE applies the LTE predicate on the "tool" field.
func ToolLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTool, v))
}

// ToolContains applies the Contains predicate on the "tool" field.
func ToolContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldTool, v))
}

// ToolHasPrefix applies the HasPrefix predicate on the "tool" field.
func ToolHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldTool, v))
}

// ToolHasSuffix applies the HasSuffix predicate on the "tool" field.
func ToolHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldTool, v))
}

// ToolEqualFold applies the EqualFold predicate on the "tool" field.
func ToolEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldTool, v))
}

// ToolContainsFold applies the ContainsFold predicate on the "tool" field.
func ToolContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldTool, v))
}

// CwdEQ applies the EQ predicate on the "cwd" field.
func CwdEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCwd, v))
}

// CwdNEQ applies the NEQ predicate on the "cwd" field.
func CwdNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldCwd, v))
}

// CwdIn applies the In predicate on the "cwd" field.
func CwdIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldCwd, vs...))
}

// CwdNotIn applies the NotIn predicate on the "cwd" field.
func CwdNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldCwd, vs...))
}

// CwdGT applies the GT predicate on the "cwd" field.
func CwdGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldCwd, v))
}

// CwdGTE applies the GTE predicate on the "cwd" field.
func CwdGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldCwd, v))
}

// CwdLT applies the LT predicate on the "cwd" field.
func CwdLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldCwd, v))
}

// CwdLTE applies the LTE predicate on the "cwd" field.
func CwdLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldCwd, v))
}

// CwdContains applies the Contains predicate on the "cwd" field.
func CwdContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldCwd, v))
}

// CwdHasPrefix applies the HasPrefix predicate on the "cwd" field.
func CwdHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldCwd, v))
}

// CwdHasSuffix applies the HasSuffix predicate on the "cwd" field.
func CwdHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldCwd, v))
}

// CwdEqualFold applies the EqualFold predicate on the "cwd" field.
func CwdEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldCwd, v))
}

// CwdContainsFold applies the ContainsFold predicate on the "cwd" field.
func CwdContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldCwd, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldProject, v))
}

// RepoOwnerEQ applies the EQ predicate on the "repo_owner" field.
func RepoOwnerEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRepoOwner, v))
}

// RepoOwnerNEQ applies the NEQ predicate on the "repo_owner" field.
func RepoOwnerNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldRepoOwner, v))
}

// RepoOwnerIn applies the In predicate on the "repo_owner" field.
func RepoOwnerIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldRepoOwner, vs...))
}

// RepoOwnerNotIn applies the NotIn predicate on the "repo_owner" field.
func RepoOwnerNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldRepoOwner, vs...))
}

// RepoOwnerGT applies the GT predicate on the "repo_owner" field.
func RepoOwnerGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldRepoOwner, v))
}

// RepoOwnerGTE applies the GTE predicate on the "repo_owner" field.
func RepoOwnerGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldRepoOwner, v))
}

// RepoOwnerLT applies the LT predicate on the "repo_owner" field.
func RepoOwnerLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldRepoOwner, v))
}

// RepoOwnerLTE applies the LTE predicate on the "repo_owner" field.
func RepoOwnerLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldRepoOwner, v))
}

// RepoOwnerContains applies the Contains predicate on the "repo_owner" field.
func RepoOwnerContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldRepoOwner, v))
}

// RepoOwnerHasPrefix applies the HasPrefix predicate on the "repo_owner" field.
func RepoOwnerHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldRepoOwner, v))
}

// RepoOwnerHasSuffix applies the HasSuffix predicate on the "repo_owner" field.
func RepoOwnerHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldRepoOwner, v))
}

// RepoOwnerEqualFold applies the EqualFold predicate on the "repo_owner" field.
func RepoOwnerEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldRepoOwner, v))
}

// RepoOwnerContainsFold applies the ContainsFold predicate on the "repo_owner" field.
func RepoOwnerContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldRepoOwner, v))
}

// RepoNameEQ applies the EQ predicate on the "repo_name" field.
func RepoNameEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRepoName, v))
}

// RepoNameNEQ applies the NEQ predicate on the "repo_name" field.
func RepoNameNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldRepoName, v))
}

// RepoNameIn applies the In predicate on the "repo_name" field.
func RepoNameIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldRepoName, vs...))
}

// RepoNameNotIn applies the NotIn predicate on the "repo_name" field.
func RepoNameNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldRepoName, vs...))
}

// RepoNameGT applies the GT predicate on the "repo_name" field.
func RepoNameGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldRepoName, v))
}

// RepoNameGTE applies the GTE predicate on the "repo_name" field.
func RepoNameGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldRepoName, v))
}

// RepoNameLT applies the LT predicate on the "repo_name" field.
func RepoNameLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldRepoName, v))
}

// RepoNameLTE applies the LTE predicate on the "repo_name" field.
func RepoNameLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldRepoName, v))
}

// RepoNameContains applies the Contains predicate on the "repo_name" field.
func RepoNameContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldRepoName, v))
}

// RepoNameHasPrefix applies the HasPrefix predicate on the "repo_name" field.
func RepoNameHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldRepoName, v))
}

// RepoNameHasSuffix applies the HasSuffix predicate on the "repo_name" field.
func RepoNameHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldRepoName, v))
}

// RepoNameEqualFold applies the EqualFold predicate on the "repo_name" field.
func RepoNameEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldRepoName, v))
}

// RepoNameContainsFold applies the ContainsFold predicate on the "repo_name" field.
func RepoNameContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldRepoName, v))
}

// RepoRemoteEQ applies the EQ predicate on the "repo_remote" field.
func RepoRemoteEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRepoRemote, v))
}

// RepoRemoteNEQ applies the NEQ predicate on the "repo_remote" field.
func RepoRemoteNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldRepoRemote, v))
}

// RepoRemoteIn applies the In predicate on the "repo_remote" field.
func RepoRemoteIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldRepoRemote, vs...))
}

// RepoRemoteNotIn applies the NotIn predicate on the "repo_remote" field.
func RepoRemoteNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldRepoRemote, vs...))
}

// RepoRemoteGT applies the GT predicate on the "repo_remote" field.
func RepoRemoteGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldRepoRemote, v))
}

// RepoRemoteGTE applies the GTE predicate on the "repo_remote" field.
func RepoRemoteGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldRepoRemote, v))
}

// RepoRemoteLT applies the LT predicate on the "repo_remote" field.
func RepoRemoteLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldRepoRemote, v))
}

// RepoRemoteLTE applies the LTE predicate on the "repo_remote" field.
func RepoRemoteLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldRepoRemote, v))
}

// RepoRemoteContains applies the Contains predicate on the "repo_remote" field.
func RepoRemoteContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldRepoRemote, v))
}

// RepoRemoteHasPrefix applies the HasPrefix predicate on the "repo_remote" field.
func RepoRemoteHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldRepoRemote, v))
}

// RepoRemoteHasSuffix applies the HasSuffix predicate on the "repo_remote" field.
func RepoRemoteHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldRepoRemote, v))
}

// RepoRemoteEqualFold applies the EqualFold predicate on the "repo_remote" field.
func RepoRemoteEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldRepoRemote, v))
}

// RepoRemoteContainsFold applies the ContainsFold predicate on the "repo_remote" field.
func RepoRemoteContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldRepoRemote, v))
}

// GitBranchEQ applies the EQ predicate on the "git_branch" field.
func GitBranchEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldGitBranch, v))
}

// GitBranchNEQ applies the NEQ predicate on the "git_branch" field.
func GitBranchNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldGitBranch, v))
}

// GitBranchIn applies the In predicate on the "git_branch" field.
func GitBranchIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldGitBranch, vs...))
}

// GitBranchNotIn applies the NotIn predicate on the "git_branch" field.
func GitBranchNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldGitBranch, vs...))
}

// GitBranchGT applies the GT predicate on the "git_branch" field.
func GitBranchGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldGitBranch, v))
}

// GitBranchGTE applies the GTE predicate on the "git_branch" field.
func GitBranchGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldGitBranch, v))
}

// GitBranchLT applies the LT predicate on the "git_branch" field.
func GitBranchLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldGitBranch, v))
}

// GitBranchLTE applies the LTE predicate on the "git_branch" field.
func GitBranchLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldGitBranch, v))
}

// GitBranchContains applies the Contains predicate on the "git_branch" field.
func GitBranchContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldGitBranch, v))
}

// GitBranchHasPrefix applies the HasPrefix predicate on the "git_branch" field.
func GitBranchHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldGitBranch, v))
}

// GitBranchHasSuffix applies the HasSuffix predicate on the "git_branch" field.
func GitBranchHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldGitBranch, v))
}

// GitBranchEqualFold applies the EqualFold predicate on the "git_branch" field.
func GitBranchEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldGitBranch, v))
}

// GitBranchContainsFold applies the ContainsFold predicate on the "git_branch" field.
func GitBranchContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldGitBranch, v))
}

// GitCommitEQ applies the EQ predicate on the "git_commit" field.
func GitCommitEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldGitCommit, v))
}

// GitCommitNEQ applies the NEQ predicate on the "git_commit" field.
func GitCommitNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldGitCommit, v))
}

// GitCommitIn applies the In predicate on the "git_commit" field.
func GitCommitIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldGitCommit, vs...))
}

// GitCommitNotIn applies the NotIn predicate on the "git_commit" field.
func GitCommitNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldGitCommit, vs...))
}

// GitCommitGT applies the GT predicate on the "git_commit" field.
func GitCommitGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldGitCommit, v))
}

// GitCommitGTE applies the GTE predicate on the "git_commit" field.
func GitCommitGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldGitCommit, v))
}

// GitCommitLT applies the LT predicate on the "git_commit" field.
func GitCommitLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldGitCommit, v))
}

// GitCommitLTE applies the LTE predicate on the "git_commit" field.
func GitCommitLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldGitCommit, v))
}

// GitCommitContains applies the Contains predicate on the "git_commit" field.
func GitCommitContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldGitCommit, v))
}

// GitCommitHasPrefix applies the HasPrefix predicate on the "git_commit" field.
func GitCommitHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldGitCommit, v))
}

// GitCommitHasSuffix applies the HasSuffix predicate on the "git_commit" field.
func GitCommitHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldGitCommit, v))
}

// GitCommitEqualFold applies the EqualFold predicate on the "git_commit" field.
func GitCommitEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldGitCommit, v))
}

// GitCommitContainsFold applies the ContainsFold predicate on the "git_commit" field.
func GitCommitContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldGitCommit, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldSessionID, v))
}

// SessionNameEQ applies the EQ predicate on the "session_name" field.
func SessionNameEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldSessionName, v))
}

// SessionNameNEQ applies the NEQ predicate on the "session_name" field.
func SessionNameNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldSessionName, v))
}

// SessionNameIn applies the In predicate on the "session_name" field.
func SessionNameIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldSessionName, vs...))
}

// SessionNameNotIn applies the NotIn predicate on the "session_name" field.
func SessionNameNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldSessionName, vs...))
}

// SessionNameGT applies the GT predicate on the "session_name" field.
func SessionNameGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldSessionName, v))
}

// SessionNameGTE applies the GTE predicate on the "session_name" field.
func SessionNameGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldSessionName, v))
}

// SessionNameLT applies the LT predicate on the "session_name" field.
func SessionNameLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldSessionName, v))
}

// SessionNameLTE applies the LTE predicate on the "session_name" field.
func SessionNameLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldSessionName, v))
}

// SessionNameContains applies the Contains predicate on the "session_name" field.
func SessionNameContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldSessionName, v))
}

// SessionNameHasPrefix applies the HasPrefix predicate on the "session_name" field.
func SessionNameHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldSessionName, v))
}

// SessionNameHasSuffix applies the HasSuffix predicate on the "session_name" field.
func SessionNameHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldSessionName, v))
}

// SessionNameEqualFold applies the EqualFold predicate on the "session_name" field.
func SessionNameEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldSessionName, v))
}

// SessionNameContainsFold applies the ContainsFold predicate on the "session_name" field.
func SessionNameContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldSessionName, v))
}

// TurnIndexEQ applies the EQ predicate on the "turn_index" field.
func TurnIndexEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTurnIndex, v))
}

// TurnIndexNEQ applies the NEQ predicate on the "turn_index" field.
func TurnIndexNEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTurnIndex, v))
}

// TurnIndexIn applies the In predicate on the "turn_index" field.
func TurnIndexIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTurnIndex, vs...))
}

// TurnIndexNotIn applies the NotIn predicate on the "turn_index" field.
func TurnIndexNotIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTurnIndex, vs...))
}

// TurnIndexGT applies the GT predicate on the "turn_index" field.
func TurnIndexGT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTurnIndex, v))
}

// TurnIndexGTE applies the GTE predicate on the "turn_index" field.
func TurnIndexGTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTurnIndex, v))
}

// TurnIndexLT applies the LT predicate on the "turn_index" field.
func TurnIndexLT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTurnIndex, v))
}

// TurnIndexLTE applies the LTE predicate on the "turn_index" field.
func TurnIndexLTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTurnIndex, v))
}

// ParentEntryIDEQ applies the EQ predicate on the "parent_entry_id" field.
func ParentEntryIDEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldParentEntryID, v))
}

// ParentEntryIDNEQ applies the NEQ predicate on the "parent_entry_id" field.
func ParentEntryIDNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldParentEntryID, v))
}

// ParentEntryIDIn applies the In predicate on the "parent_entry_id" field.
func ParentEntryIDIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldParentEntryID, vs...))
}

// ParentEntryIDNotIn applies the NotIn predicate on the "parent_entry_id" field.
func ParentEntryIDNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldParentEntryID, vs...))
}

// ParentEntryIDGT applies the GT predicate on the "parent_entry_id" field.
func ParentEntryIDGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldParentEntryID, v))
}

// ParentEntryIDGTE applies the GTE predicate on the "parent_entry_id" field.
func ParentEntryIDGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldParentEntryID, v))
}

// ParentEntryIDLT applies the LT predicate on the "parent_entry_id" field.
func ParentEntryIDLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldParentEntryID, v))
}

// ParentEntryIDLTE applies the LTE predicate on the "parent_entry_id" field.
func ParentEntryIDLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldParentEntryID, v))
}

// ParentEntryIDContains applies the Contains predicate on the "parent_entry_id" field.
func ParentEntryIDContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldParentEntryID, v))
}

// ParentEntryIDHasPrefix applies the HasPrefix predicate on the "parent_entry_id" field.
func ParentEntryIDHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldParentEntryID, v))
}

// ParentEntryIDHasSuffix applies the HasSuffix predicate on the "parent_entry_id" field.
func ParentEntryIDHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldParentEntryID, v))
}

// ParentEntryIDEqualFold applies the EqualFold predicate on the "parent_entry_id" field.
func ParentEntryIDEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldParentEntryID, v))
}

// ParentEntryIDContainsFold applies the ContainsFold predicate on the "parent_entry_id" field.
func ParentEntryIDContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldParentEntryID, v))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldHostname, v))
}

// UserEQ applies the EQ predicate on the "user" field.
func UserEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldUser, v))
}

// UserNEQ applies the NEQ predicate on the "user" field.
func UserNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldUser, v))
}

// UserIn applies the In predicate on the "user" field.
func UserIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldUser, vs...))
}

// UserNotIn applies the NotIn predicate on the "user" field.
func UserNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldUser, vs...))
}

// UserGT applies the GT predicate on the "user" field.
func UserGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldUser, v))
}

// UserGTE applies the GTE predicate on the "user" field.
func UserGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldUser, v))
}

// UserLT applies the LT predicate on the "user" field.
func UserLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldUser, v))
}

// UserLTE applies the LTE predicate on the "user" field.
func UserLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldUser, v))
}

// UserContains applies the Contains predicate on the "user" field.
func UserContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldUser, v))
}

// UserHasPrefix applies the HasPrefix predicate on the "user" field.
func UserHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldUser, v))
}

// UserHasSuffix applies the HasSuffix predicate on the "user" field.
func UserHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldUser, v))
}

// UserEqualFold applies the EqualFold predicate on the "user" field.
func UserEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldUser, v))
}

// UserContainsFold applies the ContainsFold predicate on the "user" field.
func UserContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldUser, v))
}

// ShellEQ applies the EQ predicate on the "shell" field.
func ShellEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldShell, v))
}

// ShellNEQ applies the NEQ predicate on the "shell" field.
func ShellNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldShell, v))
}

// ShellIn applies the In predicate on the "shell" field.
func ShellIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldShell, vs...))
}

// ShellNotIn applies the NotIn predicate on the "shell" field.
func ShellNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldShell, vs...))
}

// ShellGT applies the GT predicate on the "shell" field.
func ShellGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldShell, v))
}

// ShellGTE applies the GTE predicate on the "shell" field.
func ShellGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldShell, v))
}

// ShellLT applies the LT predicate on the "shell" field.
func ShellLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldShell, v))
}

// ShellLTE applies the LTE predicate on the "shell" field.
func ShellLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldShell, v))
}

// ShellContains applies the Contains predicate on the "shell" field.
func ShellContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldShell, v))
}

// ShellHasPrefix applies the HasPrefix predicate on the "shell" field.
func ShellHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldShell, v))
}

// ShellHasSuffix applies the HasSuffix predicate on the "shell" field.
func ShellHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldShell, v))
}

// ShellEqualFold applies the EqualFold predicate on the "shell" field.
func ShellEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldShell, v))
}

// ShellContainsFold applies the ContainsFold predicate on the "shell" field.
func ShellContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldShell, v))
}

// TerminalEQ applies the EQ predicate on the "terminal" field.
func TerminalEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTerminal, v))
}

// TerminalNEQ applies the NEQ predicate on the "terminal" field.
func TerminalNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTerminal, v))
}

// TerminalIn applies the In predicate on the "terminal" field.
func TerminalIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTerminal, vs...))
}

// TerminalNotIn applies the NotIn predicate on the "terminal" field.
func TerminalNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTerminal, vs...))
}

// TerminalGT applies the GT predicate on the "terminal" field.
func TerminalGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTerminal, v))
}

// TerminalGTE applies the GTE predicate on the "terminal" field.
func TerminalGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTerminal, v))
}

// TerminalLT applies the LT predicate on the "terminal" field.
func TerminalLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTerminal, v))
}

// TerminalLTE applies the LTE predicate on the "terminal" field.
func TerminalLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTerminal, v))
}

// TerminalContains applies the Contains predicate on the "terminal" field.
func TerminalContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldTerminal, v))
}

// TerminalHasPrefix applies the HasPrefix predicate on the "terminal" field.
func TerminalHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldTerminal, v))
}

// TerminalHasSuffix applies the HasSuffix predicate on the "terminal" field.
func TerminalHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldTerminal, v))
}

// TerminalEqualFold applies the EqualFold predicate on the "terminal" field.
func TerminalEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldTerminal, v))
}

// TerminalContainsFold applies the ContainsFold predicate on the "terminal" field.
func TerminalContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldTerminal, v))
}

// TerminalTitleEQ applies the EQ predicate on the "terminal_title" field.
func TerminalTitleEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTerminalTitle, v))
}

// TerminalTitleNEQ applies the NEQ predicate on the "terminal_title" field.
func TerminalTitleNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTerminalTitle, v))
}

// TerminalTitleIn applies the In predicate on the "terminal_title" field.
func TerminalTitleIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTerminalTitle, vs...))
}

// TerminalTitleNotIn applies the NotIn predicate on the "terminal_title" field.
func TerminalTitleNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTerminalTitle, vs...))
}

// TerminalTitleGT applies the GT predicate on the "terminal_title" field.
func TerminalTitleGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTerminalTitle, v))
}

// TerminalTitleGTE applies the GTE predicate on the "terminal_title" field.
func TerminalTitleGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTerminalTitle, v))
}

// TerminalTitleLT applies the LT predicate on the "terminal_title" field.
func TerminalTitleLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTerminalTitle, v))
}

// TerminalTitleLTE applies the LTE predicate on the "terminal_title" field.
func TerminalTitleLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTerminalTitle, v))
}

// TerminalTitleContains applies the Contains predicate on the "terminal_title" field.
func TerminalTitleContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldTerminalTitle, v))
}

// TerminalTitleHasPrefix applies the HasPrefix predicate on the "terminal_title" field.
func TerminalTitleHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldTerminalTitle, v))
}

// TerminalTitleHasSuffix applies the HasSuffix predicate on the "terminal_title" field.
func TerminalTitleHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldTerminalTitle, v))
}

// TerminalTitleEqualFold applies the EqualFold predicate on the "terminal_title" field.
func TerminalTitleEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldTerminalTitle, v))
}

// TerminalTitleContainsFold applies the ContainsFold predicate on the "terminal_title" field.
func TerminalTitleContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldTerminalTitle, v))
}

// TtyEQ applies the EQ predicate on the "tty" field.
func TtyEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTty, v))
}

// TtyNEQ applies the NEQ predicate on the "tty" field.
func TtyNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTty, v))
}

// TtyIn applies the In predicate on the "tty" field.
func TtyIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTty, vs...))
}

// TtyNotIn applies the NotIn predicate on the "tty" field.
func TtyNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTty, vs...))
}

// TtyGT applies the GT predicate on the "tty" field.
func TtyGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTty, v))
}

// TtyGTE applies the GTE predicate on the "tty" field.
func TtyGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTty, v))
}

// TtyLT applies the LT predicate on the "tty" field.
func TtyLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTty, v))
}

// TtyLTE applies the LTE predicate on the "tty" field.
func TtyLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTty, v))
}

// TtyContains applies the Contains predicate on the "tty" field.
func TtyContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldTty, v))
}

// TtyHasPrefix applies the HasPrefix predicate on the "tty" field.
func TtyHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldTty, v))
}

// TtyHasSuffix applies the HasSuffix predicate on the "tty" field.
func TtyHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldTty, v))
}

// TtyEqualFold applies the EqualFold predicate on the "tty" field.
func TtyEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldTty, v))
}

// TtyContainsFold applies the ContainsFold predicate on the "tty" field.
func TtyContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldTty, v))
}

// PidEQ applies the EQ predicate on the "pid" field.
func PidEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPid, v))
}

// PidNEQ applies the NEQ predicate on the "pid" field.
func PidNEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldPid, v))
}

// PidIn applies the In predicate on the "pid" field.
func PidIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldPid, vs...))
}

// PidNotIn applies the NotIn predicate on the "pid" field.
func PidNotIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldPid, vs...))
}

// PidGT applies the GT predicate on the "pid" field.
func PidGT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldPid, v))
}

// PidGTE applies the GTE predicate on the "pid" field.
func PidGTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldPid, v))
}

// PidLT applies the LT predicate on the "pid" field.
func PidLT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldPid, v))
}

// PidLTE applies the LTE predicate on the "pid" field.
func PidLTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldPid, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldPrompt, v))
}

// ResponseEQ applies the EQ predicate on the "response" field.
func ResponseEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldResponse, v))
}

// ResponseNEQ applies the NEQ predicate on the "response" field.
func ResponseNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldResponse, v))
}

// ResponseIn applies the In predicate on the "response" field.
func ResponseIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldResponse, vs...))
}

// ResponseNotIn applies the NotIn predicate on the "response" field.
func ResponseNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldResponse, vs...))
}

// ResponseGT applies the GT predicate on the "response" field.
func ResponseGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldResponse, v))
}

// ResponseGTE applies the GTE predicate on the "response" field.
func ResponseGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldResponse, v))
}

// ResponseLT applies the LT predicate on the "response" field.
func ResponseLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldResponse, v))
}

// ResponseLTE applies the LTE predicate on the "response" field.
func ResponseLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldResponse, v))
}

// ResponseContains applies the Contains predicate on the "response" field.
func ResponseContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldResponse, v))
}

// ResponseHasPrefix applies the HasPrefix predicate on the "response" field.
func ResponseHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldResponse, v))
}

// ResponseHasSuffix applies the HasSuffix predicate on the "response" field.
func ResponseHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldResponse, v))
}

// ResponseEqualFold applies the EqualFold predicate on the "response" field.
func ResponseEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldResponse, v))
}

// ResponseContainsFold applies the ContainsFold predicate on the "response" field.
func ResponseContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldResponse, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldModel, v))
}

// RawEQ applies the EQ predicate on the "raw" field.
func RawEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldRaw, v))
}

// RawNEQ applies the NEQ predicate on the "raw" field.
func RawNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldRaw, v))
}

// RawIn applies the In predicate on the "raw" field.
func RawIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldRaw, vs...))
}

// RawNotIn applies the NotIn predicate on the "raw" field.
func RawNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldRaw, vs...))
}

// RawGT applies the GT predicate on the "raw" field.
func RawGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldRaw, v))
}

// RawGTE applies the GTE predicate on the "raw" field.
func RawGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldRaw, v))
}

// RawLT applies the LT predicate on the "raw" field.
func RawLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldRaw, v))
}

// RawLTE applies the LTE predicate on the "raw" field.
func RawLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldRaw, v))
}

// RawContains applies the Contains predicate on the "raw" field.
func RawContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldRaw, v))
}

// RawHasPrefix applies the HasPrefix predicate on the "raw" field.
func RawHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldRaw, v))
}

// RawHasSuffix applies the HasSuffix predicate on the "raw" field.
func RawHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldRaw, v))
}

// RawEqualFold applies the EqualFold predicate on the "raw" field.
func RawEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldRaw, v))
}

// RawContainsFold applies the ContainsFold predicate on the "raw" field.
func RawContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldRaw, v))
}

// TokenCountInEQ applies the EQ predicate on the "token_count_in" field.
func TokenCountInEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTokenCountIn, v))
}

// TokenCountInNEQ applies the NEQ predicate on the "token_count_in" field.
func TokenCountInNEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTokenCountIn, v))
}

// TokenCountInIn applies the In predicate on the "token_count_in" field.
func TokenCountInIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTokenCountIn, vs...))
}

// TokenCountInNotIn applies the NotIn predicate on the "token_count_in" field.
func TokenCountInNotIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTokenCountIn, vs...))
}

// TokenCountInGT applies the GT predicate on the "token_count_in" field.
func TokenCountInGT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTokenCountIn, v))
}

// TokenCountInGTE applies the GTE predicate on the "token_count_in" field.
func TokenCountInGTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTokenCountIn, v))
}

// TokenCountInLT applies the LT predicate on the "token_count_in" field.
func TokenCountInLT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTokenCountIn, v))
}

// TokenCountInLTE applies the LTE predicate on the "token_count_in" field.
func TokenCountInLTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTokenCountIn, v))
}

// TokenCountOutEQ applies the EQ predicate on the "token_count_out" field.
func TokenCountOutEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTokenCountOut, v))
}

// TokenCountOutNEQ applies the NEQ predicate on the "token_count_out" field.
func TokenCountOutNEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTokenCountOut, v))
}

// TokenCountOutIn applies the In predicate on the "token_count_out" field.
func TokenCountOutIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTokenCountOut, vs...))
}

// TokenCountOutNotIn applies the NotIn predicate on the "token_count_out" field.
func TokenCountOutNotIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTokenCountOut, vs...))
}

// TokenCountOutGT applies the GT predicate on the "token_count_out" field.
func TokenCountOutGT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTokenCountOut, v))
}

// TokenCountOutGTE applies the GTE predicate on the "token_count_out" field.
func TokenCountOutGTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTokenCountOut, v))
}

// TokenCountOutLT applies the LT predicate on the "token_count_out" field.
func TokenCountOutLT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTokenCountOut, v))
}

// TokenCountOutLTE applies the LTE predicate on the "token_count_out" field.
func TokenCountOutLTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTokenCountOut, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldTags, v))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldTags, v))
}

// StarredEQ applies the EQ predicate on the "starred" field.
func StarredEQ(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldStarred, v))
}

// StarredNEQ applies the NEQ predicate on the "starred" field.
func StarredNEQ(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldStarred, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.NotPredicates(p))
}
