// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Entry is the predicate function for entry builders.
type Entry func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)
